name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
  
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
  
      - name: Build image
        run: | 
          docker build -t ${{secrets.REGISTRY_USER}}portfolio:8 .
          docker build -t ${{secrets.REGISTRY_USER}}portfolio:latest .
   
         # --- SIMPLE TRIVY SCAN STARTS HERE ---
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ secrets.REGISTRY_USER }}portfolio:${{ github.run_number }}'
          exit-code: '1' # This will fail the job if any vulnerabilities are found
          severity: 'CRITICAL,HIGH'
      

      - name: Push image 
        run: |
          docker push ${{secrets.ECR_REGISTRY}}/portfolio:8
          docker push ${{secrets.ECR_REGISTRY}}/portfolio:latest

  deploy:
    needs: build  
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
    
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
    
      - name: SSH to Server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: | 
            docker rm -f resume || true
            docker run -d --name resume -p 8080:5001 ${{secrets.ECR_REGISTRY}}/portfolio:${{github.run_number}}